---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monkale.monkale.io
  resources:
  - dnszones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monkale.monkale.io
  resources:
  - dnszones/finalizers
  verbs:
  - update
- apiGroups:
  - monkale.monkale.io
  resources:
  - dnszones/status
  verbs:
  - get
  - patch
  - update
