apiVersion: monkale.monkale.io/v1alpha1
kind: DNSConnector
metadata:
  name: coredns
  namespace: kube-system
spec:
  waitForUpdateTimeout: 120
  corednsCM: 
    name: coredns
    corefileKey: Corefile
  corednsDeployment:
    name: coredns
    type: Deployment
  corednsZoneEnaledPlugins:
  - errors
  - log