---
apiVersion: monkale.monkale.io/v1alpha1
kind: DNSZone
metadata:
  name: market-example-zone
  namespace: kube-system
spec:
  connectorName: coredns
  domain: "market.example.com"
  primaryNS:
    ipAddress: "10.100.100.254"
  respPersonEmail: "admin@example.com"

---
apiVersion: monkale.monkale.io/v1alpha1
kind: DNSZone
metadata:
  name: no-connector-test-zone
  namespace: kube-system
spec:
  connectorName: this-connector-does-not-exist
  domain: "test.com."
  primaryNS:
    ipAddress: "10.120.100.11"
  respPersonEmail: "admin@test.local"